version: '3.8'

services:
  app-cardapio-homolog:
    build:
      context: .
      args:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL_HOMOLOG}
    container_name: app-cardapio-homolog
    ports:
      - "5177:80"
    restart: always
    networks:
      - concordia-network

  app-cardapio-production:
    build:
      context: .
      args:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL_MAIN}
    container_name: app-cardapio-production
    ports:
      - "3177:80"
    restart: always
    networks:
      - concordia-network

networks:
  concordia-network:
    external: true
