name: Deploy Homolog - App Cardápio

on:
  push:
    branches:
      - homolog

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/app-cardapio-homolog:latest
          build-args: |
            VITE_API_BASE_URL=https://homolog-api-concordia.marshalltds.com/api

  deploy:
    needs: build-and-deploy
    runs-on: self-hosted
    steps:
      - name: Pull and run container
        run: |
          REPO_OWNER_LOWER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          docker pull ghcr.io/${REPO_OWNER_LOWER}/app-cardapio-homolog:latest
          docker stop app-cardapio-homolog || true
          docker rm app-cardapio-homolog || true
          docker run -d \
            --name app-cardapio-homolog \
            --restart always \
            --network concordia-network \
            -p 5176:80 \
            ghcr.io/${REPO_OWNER_LOWER}/app-cardapio-homolog:latest
